export const mainListTypes = {
  FETCH_HEROES_REQUEST: 'mainList/FETCH_HEROES_REQUEST',
  FETCH_HEROES_SUCCESS: 'mainList/FETCH_HEROES_SUCCESS',
  FETCH_HEROES_FAILURE: 'mainList/FETCH_HEROES_FAILURE',
}

export const historyListTypes = {
  FETCH_HISTORY_REQUEST: 'historyList/FETCH_HISTORY_REQUEST',
  FETCH_HISTORY_SUCCESS: 'historyList/FETCH_HISTORY_SUCCESS',
  FETCH_HISTORY_FAILURE: 'historyList/FETCH_HISTORY_FAILURE',
  ADD_TO_HISTORY: 'historyList/ADD_TO_HISTORY',
  REMOVE_FROM_HISTORY: 'historyList/REMOVE_FROM_HISTORY',
  CLEAR_HISTORY: 'historyList/CLEAR_HISTORY',
}

export const heroesTypes = {
  FETCH_HERO_REQUEST: 'heroes/FETCH_HERO_REQUEST',
  FETCH_HERO_SUCCESS: 'heroes/FETCH_HERO_SUCCESS',
  FETCH_HERO_FAILURE: 'heroes/FETCH_HERO_FAILURE',
}
